setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#colors for functional types
colours = c(  "#fe0000","#4386bb", "#56b456", "#9d58a8", "#fe870f", "#fdff39",
               "#ab6036")


#######################################################################################################
# abundance and richness pie charts Figure 2
data = read.csv("FT_richness_abundance.csv")

library(plotrix)
richness = pie3D(data$species, main = "Proportion of species per functional types", 
         explode=0.1, radius=.9, start=0.7,col = colours)
pie3D.labels(richness,labels=data$functional_types,radius=1,height=0.3,
             labelcex=1.2,labelrad=1.3,minsep=0.15)

abundance = pie3D(data$individuals, main = "Proportion individuals per functional types", 
         explode=0.1, radius=0.8,col = colours)
pie3D.labels(abundance ,labels=data$functional_types,radius=1,height=0.3,
             labelcex=1.2,labelrad=1.25,minsep=0.45)


#######################################################################################################
# abundance and richness boxplots Figure 3
library(reshape2)
library(ggplot2)
FTabundance=read.csv("FTabundance.csv")
FTabundance=melt(FTabundance)

boxplotFT_abundance = ggplot(data=FTabundance, aes(x=as.factor(variable), y=value,cex.lable=2))+ 
  geom_boxplot(cex=0.5, fill = colours)+  
  xlab ("Functional type")+ylab("Abundance")+
  theme(axis.line = element_line(),axis.text=element_text(size=12,family = "arial",color = "black"),
        axis.title=element_text(size=12,family = "arial",face = "bold"),
        panel.background = element_rect(fill = "white"))+
  scale_y_continuous(expand = c(0,0)) +ylim(c(-200, 25000)) 
boxplotFT_abundance


# boxplot for species richness
FTrichness = read.csv("FTrichness.csv")
FTrichness = melt(FTrichness)

boxplotFT_richness = ggplot(data=FTrichness, aes(x=as.factor(variable), y=value,cex.lable=2))+
  geom_boxplot(cex=0.5,fill = colours)+
  xlab ("Functional type")+ylab("Richness")+
  theme(axis.line = element_line(),axis.text=element_text(size=12,family = "arial",color = "black"),
        axis.title=element_text(size=12,family = "arial",face = "bold"),
        panel.background = element_rect(fill = "white"))+
  scale_y_continuous(expand = c(0,0)) +ylim(c(-2, 20)) 
boxplotFT_richness

gridExtra::grid.arrange(boxplotFT_abundance, boxplotFT_richness )

#######################################################################################################
#abundance anova
ftabundance = read.csv("FTabundance.csv")
melted_ftabundance = melt(ftabundance)

anova_abun = aov(value~ variable, data = melted_ftabundance)
abun_anova = summary(anova_abun)
class(abun_anova[[1]])
write.csv(abun_anova[[1]], "Abundance_ANOVA.csv")

tukey_result  =  TukeyHSD(anova_abun)
write.csv(tukey_result$variable, "Abundance_tuckey.csv")

# richness anova
ftrichness = read.csv("FTrichness.csv")
melted_ftrichness = melt(ftrichness)

anova_rich = aov(value~ variable, data = melted_ftrichness)
rich_anova= summary(anova_rich)
write.csv(rich_anova[[1]], "Richness_ANOVA.csv")

tukey_result  =  TukeyHSD(anova_rich)
write.csv(tukey_result$variable, "Richness_tuckey.csv")

#######################################################################################################
# CCA using all species and functional types Figure 4

library(tidyverse)
library(CCA)
library(ggplot2)
library(ggfortify)
library(ggrepel)
library(extrafont)


FTab_data = read.csv("FTabundance.csv")
FTab_data  =  with(FTab_data,  FTab_data[order(Location) , ])
abun = FTab_data[,-1]
row.names(abun) = FTab_data$Location

env_cca = read.csv("Impenvvariables.csv",check.names=FALSE)
env_cca  =  with(env_cca,  env_cca[order(Location) , ])
env = env_cca [,-1]
row.names(env) = env_cca$Location


library(vegan)

vare.cca  =  cca(abun~., data=env)
s = summary(vare.cca)
cca2  = vare.cca

#Get CCA scores
df_species   =  data.frame(summary(cca2)$species[,1:2])# get the species CC1 and CC2 scores
df_sites   =  data.frame(summary(cca2)$site[,1:2])# get the species CC1 and CC2 scores
df_environ   =  scores(cca2, display = 'bp') #get the environment vars CC1 and CC2 scores



cca1_varex = round(summary(cca2)$cont$importance[2,1]*100,1) #Get percentage of variance explained by first axis
cca2_varex = round(summary(cca2)$cont$importance[2,2]*100,1) #Get percentage of variance explained by second axis

#Set a scaling variable to multiply the CCA values, in order to get a very similar plot to the the one generated by plot(cca). You can adjust it according to your data
scaling_factor = 4
text_size = 5


ggplot(df_species, 
       aes(x=CCA1, y=CCA2)) + 
  #Draw lines on x = 0 and y = 0
  geom_hline(yintercept=0, 
             linetype="dashed") +
  geom_vline(xintercept=0, 
             linetype="dashed") +
  # coord_fixed()+
  #Add species text
  geom_point(data=df_species, 
             aes(x=CCA1,#Score in CCA1 to add species text
                 y=CCA2),#Score in CCA2 to add species text
             color = "red")+
  geom_text_repel(data=df_species, size = text_size,
                  aes(family="Arial",
                      x=CCA1,#Score in CCA1 to add species text
                      y=CCA2,#Score in CCA2 to add species text
                      label=rownames(df_species)),
                  # hjust=0.01*(1-sign(CCA1)),#Set the text horizontal alignment according to its position in the CCA plot
                  #vjust=-0.5*(1-sign(CCA2))),#Set the text vertical alignment according to its position in the CCA plot
                  color = "red")+
  #Add sites text
  geom_point(data=df_sites, 
             aes(x=CCA1,#Score in CCA1 to add species text
                 y=CCA2),#Score in CCA2 to add species text
             #color = "blue"
             color = 'blue'
  )+
  geom_text_repel(data=df_sites, size = text_size,
                  aes(family="Arial",
                      x=CCA1,#Score in CCA1 to add species text
                      y=CCA2,#Score in CCA2 to add species text
                      label=rownames(df_sites)),
                  # hjust=-0.01*(1-sign(CCA1)),#Set the text horizontal alignment according to its position in the CCA plot
                  #  vjust=-0.5*(1-sign(CCA2))),#Set the text vertical alignment according to its position in the CCA plot
                  #  color = "blue"
                  color = 'blue',box.padding = 0.1
  )+
  #Add environmental vars arrows
  geom_segment(data=df_environ, 
               aes(x=0, #Starting coordinate in CCA1 = 0 
                   xend=CCA1*scaling_factor,#Ending coordinate in CCA1  
                   y=0, #Start in CCA2 = 0
                   yend=CCA2*scaling_factor), #Ending coordinate in CCA2 
               color="black", #set color
               arrow=arrow(length=unit(0.01,"npc"))#Set the size of the lines that form the tip of the arrow
  )+
  # Add environmental vars text
  geom_text_repel(data=df_environ,size = text_size,
                  aes(family="Arial",
                      x=CCA1*scaling_factor,
                      y=CCA2*scaling_factor,
                      label=rownames(df_environ)),
                  # hjust=0.1*(1-sign(CCA1)),#Add the text of each environmental var at the end of the arrow
                  #  vjust=0.1*(1-sign(CCA2))),#Add the text of each environmental var at the end of the arrow
                  color="black")+
  #Set bw theme
  labs(x=paste0("CCA1 (",cca1_varex," %)"),
       y=paste0("CCA2 (",cca2_varex," %)"))+
  theme(axis.line = element_line(),axis.text=element_text(size=12,family = "arial"),
        axis.title=element_text(size=12,family = "arial",face = "bold"),
        panel.background = element_rect(fill = "white"))

#######################################################################################################
# CCA using all functional types and excluding graminoids having abundance more than 10000 individuals
# Figure 5

library(tidyverse)
library(CCA)
library(ggplot2)
library(ggfortify)
library(ggrepel)
library(extrafont)



FTab_data = read.csv("FTabundance_wo_abundant_graminoids.csv")
row.names(FTab_data) = FTab_data$Location # Giving locations as row names
FTab_data  =  (FTab_data [-1])


env_cca = read.csv("Impenvvariables.csv",check.names=FALSE)
env_cca  =  with(env_cca,  env_cca[order(Location) , ])
env = env_cca [,-1]
row.names(env) = env_cca$Location


library(vegan)
vare.cca  =  cca(FTab_data~., data=env)
s = summary(vare.cca)
summary(vare.cca)$cont
cca1  = vare.cca


#Get CCA scores
df_species   =  data.frame(summary(cca1)$species[,1:2])# get the species CC1 and CC2 scores
df_sites   =  data.frame(summary(cca1)$site[,1:2])# get the species CC1 and CC2 scores
df_environ   =  scores(cca1, display = 'bp') #get the environment vars CC1 and CC2 scores

cca1_varex = round(summary(cca1)$cont$importance[2,1]*100,1) #Get percentage of variance explained by first axis
cca2_varex = round(summary(cca1)$cont$importance[2,2]*100,1) #Get percentage of variance explained by second axis

#Set a scaling variable to multiply the CCA values, in order to get a very similar plot to the the one generated by plot(cca_model). You can adjust it according to your data
scaling_factor = 5
text_size = 5
ggplot(df_species, 
       aes(x=CCA1, y=CCA2)) + 
  #Draw lines on x = 0 and y = 0
  geom_hline(yintercept=0, 
             linetype="dashed") +
  geom_vline(xintercept=0, 
             linetype="dashed") +
  # coord_fixed()+
  #Add species text
  geom_point(data=df_species, 
             aes(x=CCA1,#Score in CCA1 to add species text
                 y=CCA2),#Score in CCA2 to add species text
             color = "red")+
  geom_text_repel(data=df_species, size=text_size,
                  aes(family="Arial",
                      x=CCA1,#Score in CCA1 to add species text
                      y=CCA2,#Score in CCA2 to add species text
                      label=rownames(df_species)),
                  # hjust=0.01*(1-sign(CCA1)),#Set the text horizontal alignment according to its position in the CCA plot
                  #vjust=-0.5*(1-sign(CCA2))),#Set the text vertical alignment according to its position in the CCA plot
                  color = "red")+
  #Add sites text
  geom_point(data=df_sites, 
             aes(x=CCA1,#Score in CCA1 to add species text
                 y=CCA2),#Score in CCA2 to add species text
             #color = "blue"
             color = 'blue'
  )+
  geom_text_repel(data=df_sites, size = text_size,
                  aes(family="Arial",
                      x=CCA1,#Score in CCA1 to add species text
                      y=CCA2,#Score in CCA2 to add species text
                      label=rownames(df_sites)),
                  # hjust=-0.01*(1-sign(CCA1)),#Set the text horizontal alignment according to its position in the CCA plot
                  #  vjust=-0.5*(1-sign(CCA2))),#Set the text vertical alignment according to its position in the CCA plot
                  #  color = "blue"
                  color = 'blue',box.padding = 0.1
  )+
  #Add environmental vars arrows
  geom_segment(data=df_environ, 
               aes(x=0, #Starting coordinate in CCA1 = 0 
                   xend=CCA1*scaling_factor,#Ending coordinate in CCA1  
                   y=0, #Start in CCA2 = 0
                   yend=CCA2*scaling_factor), #Ending coordinate in CCA2 
               color="black", #set color
               arrow=arrow(length=unit(0.01,"npc"))#Set the size of the lines that form the tip of the arrow
  )+
  # Add environmental vars text
  geom_text_repel(data=df_environ,size = text_size,
                  aes(family="Arial",
                      x=CCA1*scaling_factor,
                      y=CCA2*scaling_factor,
                      label=rownames(df_environ)),
                  # hjust=0.1*(1-sign(CCA1)),#Add the text of each environmental var at the end of the arrow
                  #  vjust=0.1*(1-sign(CCA2))),#Add the text of each environmental var at the end of the arrow
                  color="black")+
  #Set bw theme
  labs(x=paste0("CCA1 (",cca1_varex," %)"),
       y=paste0("CCA2 (",cca2_varex," %)"))+
  theme(axis.line = element_line(),axis.text=element_text(size=12,family = "arial"),
        axis.title=element_text(size=12,family = "arial",face = "bold"),
        panel.background = element_rect(fill = "white"))
######################################################